version: "3.9"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
    networks:
      - caddy_network

  wsgi_server:
    build:
      context: .
      dockerfile: Dockerfile

    command: gunicorn config.wsgi -w 2 -b 0.0.0.0 -p 8000
    restart: unless-stopped
    environment:
      - REDIS_ENDPOINT=redis://redis:6379
    depends_on:
      - redis
    networks:
      - caddy_network

  asgi_server:
    build: .
    command: daphne config.asgi:application -b 0.0.0.0 -p 8001
    restart: unless-stopped
    environment:
      - REDIS_ENDPOINT=redis://redis:6379
    depends_on:
      - redis
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
